# Generated by Django 6.0 on 2026-02-05 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('farmhouse', '0007_touristplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='farmhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='farmhouse.farmhouse'),
        ),
    ]
