# Generated by Django 6.0 on 2026-01-21 04:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tag', models.CharField(default='About Us', help_text='Small green label text', max_length=50)),
                ('main_title', models.CharField(help_text='Big heading text', max_length=200)),
                ('description', ckeditor.fields.RichTextField(help_text='You can add HTML tags, lists, bold, etc.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/images/')),
                ('video', models.FileField(blank=True, help_text='Upload mp4 video', null=True, upload_to='about/videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choos_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Example: fa-solid fa-house or lucide-home', max_length=100)),
                ('image', models.ImageField(upload_to='chosse_banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('Slot_position', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Example: fa-solid fa-house or lucide-home', max_length=100)),
                ('image', models.ImageField(upload_to='chosse_banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('Slot_position', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='Upload icon image', upload_to='about/icons/')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cms.aboutsection')),
            ],
        ),
        migrations.CreateModel(
            name='OurFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(help_text='Example: Finest Farmhouses with Food', max_length=200)),
                ('description', models.TextField(help_text='Short paragraph description')),
                ('image', models.ImageField(upload_to='our_specialty/')),
                ('is_active', models.BooleanField(default=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='our_facilities', to='cms.facilities')),
            ],
        ),
    ]
