# Generated by Django 6.0 on 2026-01-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfeature',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload icon image', null=True, upload_to='about/icons/'),
        ),
    ]
