# Generated by Django 6.0 on 2026-01-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_aboutfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: fa-solid fa-house or hero-home', max_length=100, null=True),
        ),
    ]
