# Generated by Django 6.0 on 2026-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_aboutfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoweare',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chosse_banners/'),
        ),
    ]
