# Generated by Django 6.0 on 2026-01-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_whoweare_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choos_services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chosse_banners/'),
        ),
    ]
