# Generated by Django 6.0 on 2026-01-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_choos_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutWhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='About Us', max_length=100)),
                ('main_title', models.CharField(default='Know Who We Are', max_length=200)),
                ('mission_title', models.CharField(default='Mission & Vision', max_length=200)),
                ('mission_description', models.TextField()),
                ('difference_title', models.CharField(default='How We Do It Differently', max_length=200)),
                ('difference_description', models.TextField()),
                ('image', models.ImageField(help_text='Main About Section Image', upload_to='about/')),
                ('button_text', models.CharField(default='More about us', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
