# Generated by Django 6.0 on 2026-01-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_aboutwhoweare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutwhoweare',
            options={'verbose_name': 'Know About Section', 'verbose_name_plural': 'Know About Section'},
        ),
    ]
