# Generated by Django 6.0 on 2026-02-10 12:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_aboutwhoweare_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
