# Generated by Django 6.0 on 2026-02-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_aboutsection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('farmhouses', 'Farmhouse Listing'), ('about', 'About'), ('contact', 'Contact')], max_length=50, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
