# Generated by Django 6.0 on 2026-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_pageseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('blog', 'Blog Listing'), ('farmhouses', 'Farmhouse Listing'), ('about', 'About'), ('contact', 'Contact')], max_length=50, unique=True),
        ),
    ]
