# Generated by Django 6.0 on 2026-03-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_pageseo_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('blog', 'Blog Listing'), ('farmhouses', 'Farmhouse Listing'), ('locations', 'Locations'), ('about', 'About'), ('contact', 'Contact')], max_length=50, unique=True),
        ),
    ]
