# Generated by Django 6.0 on 2026-01-07 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmhouse', '0006_remove_amenity_icon_amenity_icon_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True, help_text='Optional review message', null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='farmhouse.farmhouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='rating_images/')),
                ('active', models.BooleanField(default=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.rating')),
            ],
        ),
    ]
