# Generated by Django 6.0 on 2026-03-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='review_date',
            new_name='created_at',
        ),
    ]
