# Generated by Django 6.0 on 2026-01-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
