# Generated by Django 6.0 on 2026-03-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_meta_description_blog_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='Read time in minutes (e.g. 3)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
