# Generated by Django 6.0 on 2026-01-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities/')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Slot_position', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('distance_km', models.PositiveIntegerField(help_text='Distance from city in KM (e.g. 21)')),
                ('halls', models.PositiveIntegerField(default=1)),
                ('bedrooms', models.PositiveIntegerField(default=4)),
                ('ac_bedrooms', models.PositiveIntegerField(default=4)),
                ('short_description', models.TextField(help_text='Shown in card view')),
                ('description', models.TextField(help_text='Full farmhouse details page')),
                ('free_cancellation', models.BooleanField(default=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='farmhouses', to='farmhouse.amenity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmhouses', to='farmhouse.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmhouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='farmhouses/')),
                ('is_primary', models.BooleanField(default=False)),
                ('farmhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farmhouse.farmhouse')),
            ],
        ),
        migrations.CreateModel(
            name='FarmhousePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_day_price', models.DecimalField(decimal_places=2, help_text='Monday to Friday price', max_digits=10)),
                ('weekend_price', models.DecimalField(decimal_places=2, help_text='Saturday & Sunday price', max_digits=10)),
                ('extra_guest_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per extra guest (optional)', max_digits=10)),
                ('farmhouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='farmhouse.farmhouse')),
            ],
        ),
    ]
