# Generated by Django 6.0 on 2026-01-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0004_alter_farmhouse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='extra_guest_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmhouse',
            name='guest_count',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
