# Generated by Django 6.0 on 2026-01-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0005_farmhouse_extra_guest_count_farmhouse_guest_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.AddField(
            model_name='amenity',
            name='icon_class',
            field=models.CharField(default=1, help_text='Example: waves, bed, bath, car', max_length=100),
            preserve_default=False,
        ),
    ]
