# Generated by Django 6.0 on 2026-01-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0006_remove_amenity_icon_amenity_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Ramoji Film City', max_length=150)),
                ('image', models.ImageField(help_text='Upload place image', upload_to='tourist_places/')),
                ('subtitle', models.CharField(blank=True, help_text='Example: 0 Tour / Nearby Attraction', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tourist Place',
                'verbose_name_plural': 'Tourist Places',
                'ordering': ['-created_at'],
            },
        ),
    ]
