# Generated by Django 6.0 on 2026-02-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0008_farmhousepricing_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
