# Generated by Django 6.0 on 2026-02-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0009_farmhouse_commission_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmhouseFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('Slot_position', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
