# Generated by Django 6.0 on 2026-02-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0010_farmhousefacilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='farmhouses_facility', to='farmhouse.farmhousefacilities'),
        ),
    ]
