# Generated by Django 6.0 on 2026-02-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0011_farmhouse_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propertyrules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('active', models.BooleanField(default=True)),
                ('Slot_position', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thingstocarry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('active', models.BooleanField(default=True)),
                ('Slot_position', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='farmhouse',
            name='properyrules',
            field=models.ManyToManyField(blank=True, related_name='farmhouses_facility', to='farmhouse.propertyrules'),
        ),
        migrations.AddField(
            model_name='farmhouse',
            name='thingstocarry',
            field=models.ManyToManyField(blank=True, related_name='farmhouses_facility', to='farmhouse.thingstocarry'),
        ),
    ]
