# Generated by Django 6.0 on 2026-02-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0012_propertyrules_thingstocarry_farmhouse_properyrules_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyrules',
            old_name='Slot_position',
            new_name='slot_position',
        ),
        migrations.RenameField(
            model_name='thingstocarry',
            old_name='Slot_position',
            new_name='slot_position',
        ),
    ]
