# Generated by Django 6.0 on 2026-02-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0013_rename_slot_position_propertyrules_slot_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhouse',
            name='properyrules',
            field=models.ManyToManyField(blank=True, related_name='propertyrules', to='farmhouse.propertyrules'),
        ),
        migrations.AlterField(
            model_name='farmhouse',
            name='thingstocarry',
            field=models.ManyToManyField(blank=True, related_name='thingstocarry', to='farmhouse.thingstocarry'),
        ),
    ]
