# Generated by Django 6.0 on 2026-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0014_alter_farmhouse_properyrules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Short description for SEO (150–160 chars)'),
        ),
        migrations.AddField(
            model_name='farmhouse',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='farmhouse',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for search engines', max_length=255),
        ),
    ]
