# Generated by Django 6.0 on 2026-03-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0015_farmhouse_meta_description_farmhouse_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='check_in_time',
            field=models.TimeField(default='14:00', help_text='Example: 2:00 PM'),
        ),
        migrations.AddField(
            model_name='farmhouse',
            name='check_out_time',
            field=models.TimeField(default='11:00', help_text='Example: 11:00 AM'),
        ),
    ]
