# Generated by Django 6.0 on 2026-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0016_farmhouse_check_in_time_farmhouse_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Short description for SEO (150–160 chars)'),
        ),
        migrations.AddField(
            model_name='location',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for search engines', max_length=255),
        ),
    ]
