# Generated by Django 6.0 on 2026-03-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0017_location_meta_description_location_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Paste Google Maps embed iframe', null=True),
        ),
    ]
