# Generated by Django 6.0 on 2026-03-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0018_farmhouse_map_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='Slot_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
