# Generated by Django 6.0 on 2026-03-12 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0019_farmhouse_slot_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhouse',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'farmhouse_user': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmhouses', to=settings.AUTH_USER_MODEL),
        ),
    ]
