# Generated by Django 6.0 on 2026-03-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0021_alter_farmhouse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhouse',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=5, null=True),
        ),
    ]
