# Generated by Django 6.0 on 2026-03-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0023_homepopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepopup',
            name='farmhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popups', to='farmhouse.farmhouse'),
        ),
        migrations.AddField(
            model_name='homepopup',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popups', to='farmhouse.location'),
        ),
    ]
