# Generated by Django 6.0 on 2026-03-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0024_homepopup_farmhouse_homepopup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='breakfast_dinner_available',
            field=models.BooleanField(default=False),
        ),
    ]
