# Generated by Django 6.0 on 2026-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0025_farmhouse_breakfast_dinner_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhouse',
            name='breakfast_dinner_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
