# Generated by Django 6.0 on 2026-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0027_alter_farmhouse_breakfast_dinner_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
