# Generated by Django 6.0 on 2026-04-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0029_alter_farmhouse_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmhouseOfferPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sale', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, help_text='Example: New Year Offer', max_length=100, null=True)),
                ('farmhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='farmhouse.farmhouse')),
            ],
        ),
    ]
