# Generated by Django 6.0 on 2026-04-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0030_farmhouseofferpricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmhousepricing',
            name='sale_price',
        ),
    ]
