# Generated by Django 6.0 on 2026-04-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0031_remove_farmhousepricing_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhousepricing',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price. Overrides all prices.', max_digits=10, null=True),
        ),
    ]
