# Generated by Django 6.0 on 2026-04-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0032_farmhousepricing_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmhousepricing',
            name='sale_price',
        ),
    ]
