# Generated by Django 6.0 on 2026-04-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0034_farmhousepricing_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='weekend_days',
            field=models.JSONField(blank=True, default=list, help_text='Example: [5,6] for Fri & Sat', null=True),
        ),
    ]
