# Generated by Django 6.0 on 2026-04-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0035_farmhouse_weekend_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhouse',
            name='weekend_days',
            field=models.JSONField(blank=True, default=list, help_text='Example: [5,6] for Fri & Sat'),
        ),
    ]
