# Generated by Django 6.0 on 2026-05-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0036_alter_farmhouse_weekend_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhouse',
            name='food_menu',
            field=models.TextField(blank=True, help_text='Example: Morning: Idli,Dosa | Afternoon: Meals | Dinner: Chicken Curry', null=True),
        ),
    ]
