# Generated by Django 6.0 on 2026-01-08 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_blockeddate'),
        ('farmhouse', '0006_remove_amenity_icon_amenity_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeddate',
            name='farmhouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='farmhouse.farmhouse'),
            preserve_default=False,
        ),
    ]
