# Generated by Django 6.0 on 2026-01-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_blockeddate_farmhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Example: 10:00 AM', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Example: 09:00 AM', null=True),
        ),
    ]
