# Generated by Django 6.0 on 2026-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_check_in_time_booking_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
