# Generated by Django 6.0 on 2026-02-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_cancelled_at_booking_cancelled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin'), ('farmhouse_owner', 'Farmhouse_owner')], max_length=20, null=True),
        ),
    ]
