# Generated by Django 6.0 on 2026-02-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allow_full_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='allow_partial_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='allow_pay_at_farmhouse',
            field=models.BooleanField(default=True),
        ),
    ]
