# Generated by Django 6.0 on 2026-02-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_allow_full_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='allow_full_payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='allow_partial_payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='allow_pay_at_farmhouse',
        ),
    ]
