# Generated by Django 6.0 on 2026-02-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_booking_allow_full_payment_and_more'),
        ('farmhouse', '0008_farmhousepricing_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmhousePaymentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_pay_at_farmhouse', models.BooleanField(default=False)),
                ('allow_partial_payment', models.BooleanField(default=True)),
                ('allow_full_payment', models.BooleanField(default=True)),
                ('farmhouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_policy', to='farmhouse.farmhouse')),
            ],
        ),
    ]
