# Generated by Django 6.0 on 2026-03-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_farmhousepaymentpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='wallet_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount used from wallet for this booking', max_digits=10),
        ),
    ]
