# Generated by Django 6.0 on 2026-03-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reminder_sent',
        ),
    ]
