# Generated by Django 6.0 on 2026-03-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_booking_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='wallet_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Amount used from wallet for this booking', max_digits=10, null=True),
        ),
    ]
