# Generated by Django 6.0 on 2026-03-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_wallet_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
