# Generated by Django 6.0 on 2026-03-18 04:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual discount by admin', max_digits=10),
        ),
    ]
