# Generated by Django 6.0 on 2026-03-18 06:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_admin_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual advance amount paid', max_digits=10),
        ),
    ]
