# Generated by Django 6.0 on 2026-07-17 06:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat discount amount (e.g. ₹500)', max_digits=10),
        ),
    ]
