"""
Django settings for farmhousehyd project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path




from dotenv import load_dotenv

load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1@_wfmmx_cuuy!&_%a_dl*zh!_+)bpp!6k5w@#ga8c+g+#=q8^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
                "farmhouseshyderabad.com",
                "www.farmhouseshyderabad.com",
                "http://3.110.215.192" , 
                'localhost',
                '127.0.0.1',
                 ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'farmhouse',
    'contact',
    'user',
    "accounts",
    'blogs',
    'coupon',
    'booking',
    'rating',
    'cms',
    "farmhouse_owner",
    "superadmin_dashboard",
    
    "storages",
    
    'corsheaders',
    "django_ckeditor_5",
    
    # ✅ ADD THIS
    'django.contrib.humanize',
    
    "ckeditor",
    'rest_framework',
    
    "django.contrib.sitemaps",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farmhousehyd.urls'


AUTH_USER_MODEL = "user.User"



CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"


from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        "rest_framework.permissions.AllowAny",
    ),
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'farmhousehyd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# settings.py

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",

        "NAME": "farmhouse_hyd",        # DB NAME
        "USER": "farmhouse_user",       # DB USER
        "PASSWORD": "Farmhouse@2026!",  # DB PASSWORD
        "HOST": "3.110.215.192",            # or localhost
        "PORT": "3306",

        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "charset": "utf8mb4",
        },
    }
}

TIME_ZONE = "Asia/Kolkata"
USE_TZ = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOCAL_URL = "farmhouseshyderabad.com/"


# ================= EMAIL (SMTP) SETTINGS =================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "anushamuraboina9@gmail.com"
EMAIL_HOST_PASSWORD = "mpywwnwfrubgkxoe"

DEFAULT_FROM_EMAIL = "Farmhouses Hyderabad <anushamuraboina9@gmail.com>"

# Admin Email
ADMIN_EMAIL = "anushamuraboina9@gmail.com"

# Optional: CC emails
CC_EMAIL = ["anushamuraboina99@gmail.com"]

# =================================================================



RAZORPAY_KEY_ID = "rzp_live_SJVDXOrw6k20Yj"
RAZORPAY_KEY_SECRET = "a2oTbAtcyq3XYQsiYyib7Hhz"
RAZORPAY_WEBHOOK_SECRET = "fosufweh fsdufjhtu3u40574075jlkrwSSdsdFosdjth84j@#$5jjhgjldsg"

# ====================================


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 300,
        "width": "100%",
    }
}



CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "link", "bulletedList", "numberedList", "|",
            "blockQuote", "insertTable", "imageUpload", "|",
            "undo", "redo"
        ],
    }
}
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# # Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://3.110.215.192",
    "https://farmhouseshyderabad.com",
    # "https://5639-2404-1f00-8047-a466-dc0a-9cc6-4d68-1ae6.ngrok-free.app",
    
]


CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://3.110.215.192",
    "https://farmhouseshyderabad.com",
    # "http://127.0.0.1:9000",
    # "https://5639-2404-1f00-8047-a466-dc0a-9cc6-4d68-1ae6.ngrok-free.app",
]

# 
CSRF_COOKIE_HTTPONLY = False


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'anushamuraboina9@gmail.com'
# EMAIL_HOST_PASSWORD = 'mpywwnwfrubgkxoe'
# DEFAULT_FROM_EMAIL = 'anushamuraboina9@gmail.com'
# ADMIN_EMAIL = 'anushamuraboina9@gmail.com' 

# FRONTEND_URL = 'http://127.0.0.1:9000'  

CC_EMAIL = [
    'anushamuraboina9@gmail.com',
    'info@vivaanfarmhouse.com',
]
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True







AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True

AWS_QUERYSTRING_AUTH = False   # Optional: avoid signed URLs
AWS_DEFAULT_ACL = 'public-read'  # Optional: control file visibility

# Custom domain (Amazon S3 URL or your CloudFront if you have one)
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

# Use this only for Django 4.2+:
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "location": "media",
            "default_acl": None,
        }
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",  # Use the default static storage backend
    },
}



# MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'



# Media URL - replaces MEDIA_URL = '/media/'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

