# Generated by Django 6.0 on 2026-03-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_farmhouse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farmhouse_limit',
            field=models.PositiveIntegerField(default=3, help_text='Maximum farmhouses allowed for farmhouse owners'),
        ),
    ]
