# Generated by Django 6.0 on 2026-03-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_farmhouse_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='farmhouse_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum farmhouses allowed for farmhouse owners'),
        ),
    ]
