# Generated by Django 6.0 on 2026-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_farmhouse_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='farmhouse_limit',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Maximum farmhouses allowed for farmhouse owners', null=True),
        ),
    ]
