# Generated by Django 6.0 on 2026-03-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_farmhouse_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, help_text='Add any notes about this user', null=True),
        ),
    ]
