# Generated by Django 6.0 on 2026-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/profile/default.png', null=True, upload_to='users/profile/'),
        ),
    ]
